name: mmuphin
owner: iuc
description: "MMUPHin is an R package implementing meta-analysis methods for microbial community profiles"
homepage_url: https://huttenhower.sph.harvard.edu/mmuphin
long_description: |
    MMUPHin is a Bioconductor package implementing meta-analysis methods for microbial community profiles. It has interfaces for 
    a) covariate-controlled batch and study effect adjustment, 
    b) meta-analytic differential abundance testing, and 
    c) meta-analytic discovery of discrete (cluster-based) or 
    d) continuous unsupervised population structure.
    Overall, MMUPHin enables the normalization and combination of multiple microbial community studies. It can then help in identifying microbes, genes, or pathways that are differential with respect to combined phenotypes. 
    Finally, it can find clusters or gradients of sample types that reproduce consistently among studies
remote_repository_url: https://github.com/biobakery/MMUPHin
type: unrestricted
categories:
  - Metagenomics
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the mmuphin adjust_batch function: {{ tool_name }}"
