name: mmuphin
owner: iuc
description: "MMUPHin is an R package implementing meta-analysis methods for microbial community profiles"
homepage_url: https://huttenhower.sph.harvard.edu/mmuphin
remote_repository_url: https://github.com/biobakery/MMUPHin
type: unrestricted
categories:
  - Metagenomics
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the mmuphin adjust_batch function: {{ tool_name }}"
