categories:
- Metagenomics
description: |
    Gene Allele Mutation Microbial Assessment 
long_description: |
    GAMMA (Gene Allele Mutation Microbial Assessment) is a command line tool that finds gene 
    matches in microbial genomic data using protein coding (rather than nucleotide) identity, and 
    then translates and annotates the match by providing the type (i.e., mutant, truncation, etc.) 
    and a translated description (i.e., Y190S mutant, truncation at residue 110, etc.). Because 
    microbial gene families often have multiple alleles and existing databases are rarely exhaustive, 
    GAMMA is helpful in both identifying and explaining how unique alleles differ from their closest 
    known matches.    
name: gamma
owner: iuc
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/main/tools/gamma/"
homepage_url: "https://github.com/rastanton/GAMMA"
type: unrestricted
