name: data_manager_deeparg
owner: iuc
description: "Download deepARG database"
homepage_url: "https://github.com/gaarangoa/deeparg"
long_description: |
    Data manager to download the database needed for deepARG to run (datasets, databases, models)
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_deeparg"
type: unrestricted
categories:
- Data Managers
suite:
  name: "suite_deeparg"
  description: "DeepARG is a deep learning based approach to predict Antibiotic Resistance Genes (ARGs) from metagenomes with short or long sequences"