name: data_manager_deeparg
owner: iuc
description: "DeepARG for Antibiotic Resistance Genes (ARGs) prediction"
homepage_url: "https://github.com/gaarangoa/deeparg"
long_description: |
    A deep learning based approach to predict Antibiotic Resistance Genes (ARGs) from metagenomes with short or long sequences
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_deeparg"
type: unrestricted
categories:
- Data Managers