name: data_manager_build_staramr
owner: iuc
description: "Scan genome contigs against the ResFinder, PlasmidFinder, and PointFinder antimicrobial resistance databases."
homepage_url: "https://github.com/phac-nml/staramr"
long_description: |
    staramr - Scans genome contigs (in FASTA format) against the ResFinder, 
    PlasmidFinder, and PointFinder databases to search for antimicrobial resistance genomes. 
    Makes predictions of the drugs these genes give resistance to.
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_build_staramr"
type: unrestricted
categories:
- Data Managers