name: constava
owner: iuc
description: "Calculate 'conformational states probability' and 'conformational state variability' from a protein structure ensemble"
long_description: |
  Constava analyzes conformational ensembles calculating conformational state propensities and conformational state variability.
  The conformational state propensities indicate the likelihood of a residue residing in a given conformational state,
  while the conformational state variability is a measure of the residues ability to transition between conformational states.

  Each conformational state is a statistical model of based on the backbone dihedrals (phi, psi).
  The default models were derived from an analysis of NMR ensembles and chemical shifts.
  To analyze a conformational ensemble, the phi- and psi-angles for each conformational state in the ensemble need to be provided.

  As input data Constava needs the backbone dihedral angles extracted from the conformational ensemble.
  These dihedrals can be obtained using GROMACS' gmx chi module (set `--input-format=xvg`) or using the Constava dihedrals submodule,
  which supports a wide range of MD and structure formats.
categories:
- Statistics
- Proteomics
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/constava
homepage_url: https://github.com/bio2byte/constava
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}"
