categories: [Systems Biology, Data Export, Graphics]
description: Galaxy wrapper for the PhysiCell data output loader command line commands.
homepage_url: https://github.com/elmbeech/physicelldataloader
long_description: Galaxy wrapper for the pcdl PhysiCell Data Loader command line commands.
  Pcdl is paramount for downstream analysis from PhysiCell output. As such, the pcdl
  Galaxy tools are useful if you work with the interactive PhysiCell Studio Galaxy
  tool.
name: pcdl
owner: bb-8
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/pcdl/.shed.yml
type: unrestricted
