categories:
- Statistics
- Fastq Manipulation
description: |
    A tool for quick quality assessment of cram and bam files, intended for long read sequencing. 
long_description: |
    Cramino is a tool 



to compare multiple runs of long read sequencing 
    data and alignments. It creates violin plots or box plots of length, quality 
    and percent identity and creates dynamic, overlaying read length 
    histograms and a cumulative yield plot.  

It is part of the
    NanoPack tool suite for visualizing and processing long read
    sequencing data.
name: cramino
owner: iuc
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/main/tools/cramino/"
homepage_url: "https://github.com/wdecoster/cramino"
type: unrestricted
