categories:
- Next Gen Mappers
description: LexicMap is a nucleotide sequence alignment tool for efficiently querying genomes. 
long_description: |
  LexicMap is a nucleotide sequence alignment tool for efficiently querying gene, plasmid, virus, or long-read sequences (>100 bp) against up to millions of prokaryotic genomes.
name: lexicmap
owner: iuc
remote_repository_url: https://github.com/shenwei356/LexicMap
homepage_url: https://bioinf.shenwei.me/LexicMap/
type: unrestricted