name: sequali
owner: devteam
description: Fast sequencing data quality metrics for short and long reads
homepage_url: https://sequali.readthedocs.io/
long_description: |
  Fast sequencing data quality metrics for short and long reads
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/sequali
categories:
- Fastq Manipulation
