name: sequali
owner: rhpvorderman
description: Fast sequencing data quality metrics for short and long reads
homepage_url: https://sequali.readthedocs.io/
long_description: |
  Fast sequencing data quality metrics for short and long reads
remote_repository_url: https://github.com/rhpvorderman/sequali
categories:
- Fastq Manipulation
