name: deeparg
owner: iuc
long_description: |
  A deep learning based approach to predict Antibiotic Resistance Genes (ARGs) from metagenomes
categories:
- Sequence Analysis
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/deeparg
homepage_url: https://github.com/gaarangoa/deeparg
type: unrestricted
