name: maplot
owner: iuc
description: Generate MA plots for visualizing data distributions using Plotly or Matplotlib.
homepage_url: https://github.com/galaxyproject/tools-iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc
type: unrestricted
categories:
  - Visualization
  - Statistics
license: MIT
summary: A Galaxy tool for generating MA plots with customizable parameters and support for multiple backends.
maintainers:
  - hechth
  - KristinaGomoryova