name: microDecon
owner: iuc
description: An R package for removing contamination from metabarcoding (e.g., microbiome) datasets post-sequencing
long_description: An R package for removing contamination from metabarcoding (e.g., microbiome) datasets post-sequencing
homepage_url: https://github.com/donaldtmcknight/microDecon
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/micro_decon/
categories:
  - Metabarcoding
