# Index format
main-version = 3
minor-version = 4
# LexicHash
max-K = 31
masks = 20000
rand-seed = 1
# Seed distance
max-seed-dist = 100
seed-dist-in-desert = 50
# Seeds (k-mer-value data) files
chunks = 1
index-partitions = 4096
# Input genomes
input-genomes = 2
# Input bases
input-bases = 21660
# Genome data. 
# 'genomes' might be larger than 'input-genomes', as some big fragmented genomes are split into multiple chunks.
# In this case, 'genome-batch-size' is not accurate, being variable in different batches.
genomes = 2
genome-batch-size = 2
genome-batches = 1
contig-interval = 1000
