name: icescreen
owner: iuc
description: identification of ICEs and IMEs in Bacillota genomes.
homepage_url: https://icescreen.migale.inrae.fr/
long_description: |
 ICEscreen identifies Integrative Conjugative Elements (ICEs) and Integrative Mobilizable Elements (IMEs) in Bacillota genomes.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/icescreen
type: unrestricted
categories:
- Genome annotation
